import { parseKubernetesYaml } from './yaml.js'
import { applyKubernetesObjects, kubeObjectKey } from './objects.js'
import { reconcileKubernetes, getDeploymentPods } from './reconcile.js'
import { kubeJson, kubeTable } from './format.js'

const aliases = { pod: 'Pod', pods: 'Pod', deployment: 'Deployment', deployments: 'Deployment', service: 'Service', services: 'Service', namespace: 'Namespace', namespaces: 'Namespace', replicaset: 'ReplicaSet', replicasets: 'ReplicaSet', node: 'Node', nodes: 'Node', event: 'Event', events: 'Event' }
const out = text => ({ text, kind: 'out' }); const err = text => ({ text, kind: 'err' })
function opts(tokens) { let namespace; let context; const rest = []; for (let i=0;i<tokens.length;i++) { const x=tokens[i]; if (x==='-n'||x==='--namespace'||x==='--context') { const v=tokens[++i]; if (!v) return { error: `argument ${x} requires a value` }; const key=x==='--context'?'context':'namespace'; if ((key==='context'?context:namespace)!==undefined) return { error: `duplicate ${x}` }; if(key==='context') context=v; else namespace=v } else rest.push(x) } return { rest, namespace, context } }
function selected(run, options) { const name = options.context ?? run.runtime.kubernetes.currentContext; if (!name) return { error: 'No current Kubernetes context is configured.' }; const context = run.runtime.kubernetes.contexts[name]; if (!context) return { error: `Context '${name}' was not found.` }; return { clusterId: context.clusterId, namespace: options.namespace ?? context.namespace } }
function result(run, lines, effects) { return { sandbox: run.sandbox, lines, events: [], latencyMs: 0, ...(effects ? { effects } : {}) } }
export function runKubectl(sandbox, tokens, { run, lab } = {}) { if (lab?.capabilities?.kubernetes !== true || !run?.runtime?.kubernetes) return { sandbox, lines:[err('kubectl is available only in a Kubernetes Lab.')], events:[],latencyMs:0 }; const parsed=opts(tokens); if(parsed.error) return result(run,[err(parsed.error)]); const [verb,...args]=parsed.rest; const context=selected(run,parsed); if (verb==='config') { if(args[0]==='current-context') return result(run,[out(run.runtime.kubernetes.currentContext ?? '')]); if(args[0]==='get-contexts') return result(run,[out(Object.keys(run.runtime.kubernetes.contexts).join('\n'))]); if(args[0]==='use-context' && args[1] && run.runtime.kubernetes.contexts[args[1]]) { const k={...run.runtime.kubernetes,currentContext:args[1]}; return result(run,[out(`Switched to context \"${args[1]}\".`)],[{type:'kubernetes-state',kubernetes:k,nextSequence:run.nextSequence}]) } if(args[0]==='set-context'&&args.includes('--current')&&args.includes('--namespace')) { const ns=args[args.indexOf('--namespace')+1]; const k=structuredClone(run.runtime.kubernetes); if(!k.currentContext)return result(run,[err('No current Kubernetes context is configured.')]); k.contexts[k.currentContext].namespace=ns; return result(run,[out(`Context namespace set to ${ns}.`)],[{type:'kubernetes-state',kubernetes:k,nextSequence:run.nextSequence}]) } return result(run,[err('Unsupported kubectl config command.')]) }
 if(context.error) return result(run,[err(`Error: ${context.error}`)]); const state=run.runtime.kubernetes.clusters[context.clusterId]; if(!state)return result(run,[err('Error: The selected Kubernetes cluster is unavailable.')]);
 if(verb==='get') { const kind=aliases[args[0]]; if(!kind)return result(run,[err('Unsupported resource type.')]); const name=args[1]; const resources=kind==='Pod'?getDeploymentPods(run,context.clusterId,context.namespace,args[1] ?? '').length&&args[1]?getDeploymentPods(run,context.clusterId,context.namespace,args[1]):Object.values(state.resources).filter(x=>x.kind===kind&&(kind==='Namespace'||x.metadata.namespace===context.namespace)):Object.values(state.resources).filter(x=>x.kind===kind&&(kind==='Namespace'||x.metadata.namespace===context.namespace)); const picked=name&&kind!=='Pod'?resources.filter(x=>x.metadata.name===name):resources; return result(run,[out(kubeTable(picked))]) }
 if(verb==='apply') { const files=[]; for(let i=0;i<args.length;i++)if(args[i]==='-f')files.push(args[++i]); if(!files.length)return result(run,[err('apply requires -f SAVED_PATH.')]); const docs=[]; const locations=[]; for(const file of files.flatMap(f=>f==='k8s/'?Object.keys(run.project.savedFiles).filter(p=>p.startsWith('k8s/')).sort():[f])) { const parsedYaml=parseKubernetesYaml(run.project.savedFiles[file],file); if(parsedYaml.diagnostics.length)return result(run,[err(parsedYaml.diagnostics[0].message)]); docs.push(...parsedYaml.documents);locations.push(...parsedYaml.locations) } const applied=applyKubernetesObjects(run,docs,{clusterId:context.clusterId,namespace:parsed.namespace,locations},lab); const next=reconcileKubernetes(applied.run,lab); const effects=[{type:'kubernetes-state',kubernetes:next.runtime.kubernetes,nextSequence:next.nextSequence}]; if(applied.diagnostics.length)return result(run,applied.lines.concat(err(`Error: ${applied.diagnostics[0].message}`)),effects); return result(run,applied.lines,effects) }
 if(verb==='delete'&&args[0]==='pod'&&args[1]) { const key=kubeObjectKey('Pod',context.namespace,args[1]); const existing=state.resources[key]; if(!existing)return result(run,[err(`Pod '${args[1]}' was not found.`)]); const next=structuredClone(run); const nextState=next.runtime.kubernetes.clusters[context.clusterId]; const controller=existing.metadata.ownerReferences?.[0]; const managed=controller?.kind==='ReplicaSet' && Object.values(nextState.resources).some(item=>item.kind==='ReplicaSet'&&item.metadata.uid===controller.uid&&item.metadata.ownerReferences?.some(ref=>ref.kind==='Deployment')); if(managed) { nextState.receipts.push({cause:'pod-delete',deletedPodUid:existing.metadata.uid,deletedPodName:existing.metadata.name,replacementPodUid:null,replacementPodName:null}); if(nextState.receipts.length>100)nextState.receipts.shift() } delete nextState.resources[key]; delete nextState.podSnapshots[existing.metadata.uid]; const reconciled=reconcileKubernetes(next,lab); return result(run,[out(`pod \"${args[1]}\" deleted`)],[{type:'kubernetes-state',kubernetes:reconciled.runtime.kubernetes,nextSequence:reconciled.nextSequence}]) }
 return result(run,[err('Unsupported kubectl command.')]) }
